spring:
  datasource:

    url: jdbc:postgresql://db.jjcijtltmmabaqzkypdi.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: Leprojet2EpfCore
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

