version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_epfcore
    restart: always
    environment:
      POSTGRES_DB: epfcore_db
      POSTGRES_USER: epfuser
      POSTGRES_PASSWORD: epfpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_epfcore
    restart: always
    ports:
      - "8081:8080"


volumes:
  postgres_data: